name: Build & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.AUTO_COMMIT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Format JSON
        run: npm run format

      - name: Check for duplicates
        run: npm run test:validate

      - name: Update Markdown
        run: npm run markdown

      - name: Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'style: apply automatic formatting'
          file_pattern: 'README.md data/*.json'

      - name: Run build
        run: npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./.build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: .build/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
