name: Static Analysis

on:
  push:
  pull_request:

jobs:

  json-schema:
    runs-on: ubuntu-latest

    name: JSON Schema

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Run JSON schema validation
        run: npm run test:schema:ci

      - name: Run JSON schema validation (strict ids)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run test:schema

  validate:
    runs-on: ubuntu-latest

    name: Validate

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Run validation script
        run: npm run test:validate

  format:
    runs-on: ubuntu-latest

    name: Format

    if: github.event_name == 'push'

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Run formatting script
        run: npm run format
